name: SonarQube Scan

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v3
        env:
          SONAR_TOKEN: sqp_2b602a974eff1ac89a93ce6f2e68
          SONAR_HOST_URL: https://lukewarm-unvented-latch.ngrok-free.dev 
